version: '3'
services:
  mysql:
    image: "mysql:5.7"
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=espresso
      - MYSQL_USER=coffee
      - MYSQL_PASSWORD=aeropress
      - MYSQL_DATABASE=coffeetime
    volumes:
      - "./scripts/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      - "./scripts/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
